-- ═══════════════════════════════════════════════════════════════════════════
-- ChantierPro — Seed catalogue articles BTP (~500 références)
-- À coller dans Supabase → SQL Editor → Run APRÈS la migration table.
-- ═══════════════════════════════════════════════════════════════════════════
-- Tous les articles sont user_id = NULL (catalogue partagé global).
-- Prix HT moyens marché Point P / Gedimat / Brico Dépôt 2024-2025.
-- Réutiliser ON CONFLICT DO NOTHING n'est pas possible (id auto), donc le seed
-- est NON IDEMPOTENT : rejouer = doublons. À exécuter une seule fois.
-- ═══════════════════════════════════════════════════════════════════════════

-- Garde-fou : si la table contient déjà > 0 articles globaux, on ne rejoue pas.
-- (Désactiver le DO si on veut forcer un re-seed après TRUNCATE manuel.)
DO $$
BEGIN
  IF (SELECT count(*) FROM public.articles_catalogue WHERE user_id IS NULL) > 0 THEN
    RAISE NOTICE 'Catalogue articles déjà peuplé — seed ignoré (TRUNCATE pour rejouer).';
    RETURN;
  END IF;

INSERT INTO public.articles_catalogue (libelle, categorie, sous_categorie, unite, prix_achat_ht, fournisseur_default, conditionnement, tva_pct) VALUES
-- ═══ PLOMBERIE — 70 articles ═══
('Bonde siphoïde Ø90 extra-plate chromée', 'Plomberie', 'Bonde', 'U', 28.00, 'Point P', 'Pièce', 20),
('Bonde de douche Ø90 horizontale inox', 'Plomberie', 'Bonde', 'U', 32.00, 'Point P', 'Pièce', 20),
('Bonde lavabo laiton chromé', 'Plomberie', 'Bonde', 'U', 18.50, 'Brico Dépôt', 'Pièce', 20),
('Bonde évier Ø90 inox panier', 'Plomberie', 'Bonde', 'U', 22.00, 'Gedimat', 'Pièce', 20),
('Siphon lavabo PVC Ø32', 'Plomberie', 'Siphon', 'U', 6.50, 'Brico Dépôt', 'Pièce', 20),
('Siphon évier double cuve Ø40', 'Plomberie', 'Siphon', 'U', 14.00, 'Point P', 'Pièce', 20),
('Siphon machine à laver droit Ø40', 'Plomberie', 'Siphon', 'U', 9.50, 'Brico Dépôt', 'Pièce', 20),
('Siphon de sol Ø100 fonte', 'Plomberie', 'Siphon', 'U', 38.00, 'Point P', 'Pièce', 20),
('Mitigeur lavabo monocommande chromé', 'Plomberie', 'Mitigeur', 'U', 65.00, 'Point P', 'Pièce', 20),
('Mitigeur évier bec haut chromé', 'Plomberie', 'Mitigeur', 'U', 78.00, 'Gedimat', 'Pièce', 20),
('Mitigeur thermostatique douche encastré', 'Plomberie', 'Mitigeur', 'U', 145.00, 'Point P', 'Pièce', 20),
('Mitigeur baignoire colonne thermostat', 'Plomberie', 'Mitigeur', 'U', 220.00, 'Point P', 'Pièce', 20),
('Robinet d''arrêt 1/4 tour 1/2"', 'Plomberie', 'Robinet', 'U', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Robinet équerre 12x17 chromé', 'Plomberie', 'Robinet', 'U', 6.00, 'Brico Dépôt', 'Pièce', 20),
('Robinet sortie murale auto-perçant', 'Plomberie', 'Robinet', 'U', 14.50, 'Point P', 'Pièce', 20),
('Tube cuivre Ø14 écroui (par ml)', 'Plomberie', 'Tube cuivre', 'ml', 6.50, 'Point P', '4ml', 20),
('Tube cuivre Ø16 écroui (par ml)', 'Plomberie', 'Tube cuivre', 'ml', 7.50, 'Point P', '4ml', 20),
('Tube cuivre Ø22 écroui (par ml)', 'Plomberie', 'Tube cuivre', 'ml', 11.00, 'Point P', '4ml', 20),
('Tube PER Ø16 barrière O2 couronne 50m', 'Plomberie', 'Tube PER', 'ml', 2.20, 'Brico Dépôt', 'Couronne 50m', 20),
('Tube PER Ø20 barrière O2 couronne 25m', 'Plomberie', 'Tube PER', 'ml', 2.80, 'Brico Dépôt', 'Couronne 25m', 20),
('Tube PER Ø25 couronne 25m', 'Plomberie', 'Tube PER', 'ml', 3.80, 'Brico Dépôt', 'Couronne 25m', 20),
('Tube multicouche Ø16 alu/PER (par ml)', 'Plomberie', 'Multicouche', 'ml', 3.50, 'Point P', '5ml', 20),
('Tube multicouche Ø20 alu/PER (par ml)', 'Plomberie', 'Multicouche', 'ml', 4.50, 'Point P', '5ml', 20),
('Tube multicouche Ø26 alu/PER (par ml)', 'Plomberie', 'Multicouche', 'ml', 6.50, 'Point P', '5ml', 20),
('Tube PVC évacuation Ø32 (par ml)', 'Plomberie', 'PVC évac', 'ml', 2.80, 'Brico Dépôt', '2ml', 20),
('Tube PVC évacuation Ø40 (par ml)', 'Plomberie', 'PVC évac', 'ml', 3.50, 'Brico Dépôt', '4ml', 20),
('Tube PVC évacuation Ø50 (par ml)', 'Plomberie', 'PVC évac', 'ml', 4.50, 'Brico Dépôt', '4ml', 20),
('Tube PVC évacuation Ø80 (par ml)', 'Plomberie', 'PVC évac', 'ml', 6.80, 'Point P', '4ml', 20),
('Tube PVC évacuation Ø100 SN8 (par ml)', 'Plomberie', 'PVC évac', 'ml', 8.50, 'Point P', '4ml', 20),
('Tube PVC évacuation Ø125 (par ml)', 'Plomberie', 'PVC évac', 'ml', 13.50, 'Point P', '4ml', 20),
('Coude PVC 90° Ø40 mâle/femelle', 'Plomberie', 'Raccord PVC', 'U', 1.80, 'Brico Dépôt', 'Pièce', 20),
('Coude PVC 90° Ø100 mâle/femelle', 'Plomberie', 'Raccord PVC', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Té PVC 87°30 Ø100 femelle', 'Plomberie', 'Raccord PVC', 'U', 6.80, 'Point P', 'Pièce', 20),
('Réduction PVC Ø100/40', 'Plomberie', 'Raccord PVC', 'U', 2.50, 'Brico Dépôt', 'Pièce', 20),
('Manchon PVC Ø100', 'Plomberie', 'Raccord PVC', 'U', 2.20, 'Brico Dépôt', 'Pièce', 20),
('Tampon hermétique PVC Ø100', 'Plomberie', 'Raccord PVC', 'U', 4.80, 'Point P', 'Pièce', 20),
('Colle PVC pot 250ml type N', 'Plomberie', 'Colle', 'U', 8.50, 'Brico Dépôt', 'Pot 250ml', 20),
('Raccord laiton 16x21 mâle pour cuivre 14', 'Plomberie', 'Raccord cuivre', 'U', 3.50, 'Point P', 'Pièce', 20),
('Té cuivre 14-14-14 à braser', 'Plomberie', 'Raccord cuivre', 'U', 2.20, 'Point P', 'Pièce', 20),
('Coude cuivre 90° Ø14 à braser', 'Plomberie', 'Raccord cuivre', 'U', 1.20, 'Point P', 'Pièce', 20),
('Coude cuivre 90° Ø16 à braser', 'Plomberie', 'Raccord cuivre', 'U', 1.50, 'Point P', 'Pièce', 20),
('Manchon cuivre Ø16 réduction Ø14', 'Plomberie', 'Raccord cuivre', 'U', 1.80, 'Point P', 'Pièce', 20),
('Raccord push-fit PER Ø16', 'Plomberie', 'Raccord PER', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Raccord push-fit PER Ø20', 'Plomberie', 'Raccord PER', 'U', 6.50, 'Brico Dépôt', 'Pièce', 20),
('Té PER push-fit 16-16-16', 'Plomberie', 'Raccord PER', 'U', 7.50, 'Brico Dépôt', 'Pièce', 20),
('Té multicouche à sertir 16-16-16', 'Plomberie', 'Raccord MC', 'U', 8.50, 'Point P', 'Pièce', 20),
('Coude multicouche à sertir 90° Ø16', 'Plomberie', 'Raccord MC', 'U', 5.50, 'Point P', 'Pièce', 20),
('Nourrice PER 4 départs M1"', 'Plomberie', 'Nourrice', 'U', 38.00, 'Point P', 'Pièce', 20),
('Nourrice multicouche 8 départs', 'Plomberie', 'Nourrice', 'U', 95.00, 'Point P', 'Pièce', 20),
('Vase d''expansion sanitaire 8L', 'Plomberie', 'Vase expansion', 'U', 38.00, 'Point P', 'Pièce', 20),
('Vase d''expansion chauffage 18L', 'Plomberie', 'Vase expansion', 'U', 78.00, 'Point P', 'Pièce', 20),
('Groupe sécurité chauffe-eau 7 bar', 'Plomberie', 'Sécurité', 'U', 32.00, 'Brico Dépôt', 'Pièce', 20),
('Réducteur de pression Ø3/4"', 'Plomberie', 'Sécurité', 'U', 65.00, 'Point P', 'Pièce', 20),
('Anode magnésium chauffe-eau 200L', 'Plomberie', 'Sécurité', 'U', 14.00, 'Brico Dépôt', 'Pièce', 20),
('Joint fibre 12x17 jaune (boîte 100)', 'Plomberie', 'Joint', 'boîte', 8.50, 'Brico Dépôt', 'Boîte 100', 20),
('Joint fibre 20x27 (boîte 100)', 'Plomberie', 'Joint', 'boîte', 12.00, 'Brico Dépôt', 'Boîte 100', 20),
('Joint torique nitrile assortiment 100', 'Plomberie', 'Joint', 'boîte', 14.50, 'Brico Dépôt', 'Boîte 100', 20),
('Filasse 100g cordage chanvre', 'Plomberie', 'Étanchéité', 'U', 6.50, 'Brico Dépôt', '100g', 20),
('Pâte d''étanchéité Loctite 55 150m', 'Plomberie', 'Étanchéité', 'U', 14.00, 'Brico Dépôt', 'Bobine 150m', 20),
('Téflon ruban 12mx12mm', 'Plomberie', 'Étanchéité', 'U', 1.80, 'Brico Dépôt', 'Rouleau', 20),
('Pompe de relevage WC broyeur', 'Plomberie', 'Pompe', 'U', 385.00, 'Point P', 'Pièce', 20),
('Pompe de surface 800W jet', 'Plomberie', 'Pompe', 'U', 195.00, 'Brico Dépôt', 'Pièce', 20),
('Surpresseur 100L cuve à vessie', 'Plomberie', 'Pompe', 'U', 385.00, 'Point P', 'Pièce', 20),
('Adoucisseur d''eau 25L mono-bac', 'Plomberie', 'Traitement eau', 'U', 980.00, 'Point P', 'Pièce', 20),
('Filtre anti-tartre polyphosphate 3/4"', 'Plomberie', 'Traitement eau', 'U', 195.00, 'Point P', 'Pièce', 20),
('Cartouche filtre eau 9 pouces 5µm', 'Plomberie', 'Filtre', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Compteur d''eau divisionnaire DN15', 'Plomberie', 'Compteur', 'U', 38.00, 'Point P', 'Pièce', 20),
('Clapet anti-retour Ø3/4"', 'Plomberie', 'Sécurité', 'U', 12.50, 'Brico Dépôt', 'Pièce', 20),
('Vanne sphère 1/2" laiton MM', 'Plomberie', 'Vanne', 'U', 6.80, 'Brico Dépôt', 'Pièce', 20),
('Vanne sphère 3/4" laiton MM', 'Plomberie', 'Vanne', 'U', 8.50, 'Brico Dépôt', 'Pièce', 20),

-- ═══ SANITAIRE — 40 articles ═══
('WC à poser sortie horizontale céramique blanc', 'Sanitaire', 'WC', 'U', 125.00, 'Brico Dépôt', 'Pièce', 20),
('WC à poser sortie verticale céramique blanc', 'Sanitaire', 'WC', 'U', 145.00, 'Point P', 'Pièce', 20),
('WC suspendu céramique sans bride', 'Sanitaire', 'WC', 'U', 285.00, 'Point P', 'Pièce', 20),
('Bâti-support WC suspendu autoportant Geberit', 'Sanitaire', 'WC', 'U', 385.00, 'Point P', 'Pièce', 20),
('Plaque commande double touche chromée', 'Sanitaire', 'WC', 'U', 95.00, 'Point P', 'Pièce', 20),
('Plaque commande blanche basique', 'Sanitaire', 'WC', 'U', 45.00, 'Brico Dépôt', 'Pièce', 20),
('Abattant WC frein de chute blanc', 'Sanitaire', 'WC', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Abattant WC haut de gamme silencieux', 'Sanitaire', 'WC', 'U', 95.00, 'Point P', 'Pièce', 20),
('Réservoir WC bas double touche 3/6L', 'Sanitaire', 'WC', 'U', 55.00, 'Brico Dépôt', 'Pièce', 20),
('Lavabo céramique sur colonne 60cm blanc', 'Sanitaire', 'Lavabo', 'U', 85.00, 'Brico Dépôt', 'Pièce', 20),
('Lavabo encastré 55cm céramique blanc', 'Sanitaire', 'Lavabo', 'U', 95.00, 'Point P', 'Pièce', 20),
('Vasque à poser ronde céramique blanc', 'Sanitaire', 'Lavabo', 'U', 125.00, 'Point P', 'Pièce', 20),
('Vasque à poser rectangle 60cm noir mat', 'Sanitaire', 'Lavabo', 'U', 195.00, 'Point P', 'Pièce', 20),
('Lavabo double vasque 120cm céramique', 'Sanitaire', 'Lavabo', 'U', 285.00, 'Point P', 'Pièce', 20),
('Colonne porte-vasque céramique blanc', 'Sanitaire', 'Lavabo', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Receveur douche acrylique 80x80 blanc extra-plat', 'Sanitaire', 'Receveur', 'U', 145.00, 'Point P', 'Pièce', 20),
('Receveur douche acrylique 90x90 blanc extra-plat', 'Sanitaire', 'Receveur', 'U', 165.00, 'Point P', 'Pièce', 20),
('Receveur douche céramique 90x90 antidérapant', 'Sanitaire', 'Receveur', 'U', 240.00, 'Point P', 'Pièce', 20),
('Receveur douche 120x80 résine pierre noir', 'Sanitaire', 'Receveur', 'U', 385.00, 'Point P', 'Pièce', 20),
('Receveur douche 140x90 céramique blanc', 'Sanitaire', 'Receveur', 'U', 320.00, 'Point P', 'Pièce', 20),
('Caniveau de douche linéaire inox 70cm', 'Sanitaire', 'Receveur', 'U', 195.00, 'Point P', 'Pièce', 20),
('Baignoire acrylique 170x70 blanc', 'Sanitaire', 'Baignoire', 'U', 245.00, 'Brico Dépôt', 'Pièce', 20),
('Baignoire acrylique 180x80 blanc', 'Sanitaire', 'Baignoire', 'U', 320.00, 'Point P', 'Pièce', 20),
('Baignoire balnéo 170x80 12 jets', 'Sanitaire', 'Baignoire', 'U', 1850.00, 'Point P', 'Pièce', 20),
('Tablier acrylique baignoire 170x70', 'Sanitaire', 'Baignoire', 'U', 78.00, 'Brico Dépôt', 'Pièce', 20),
('Pieds réglables baignoire (jeu de 4)', 'Sanitaire', 'Baignoire', 'U', 24.00, 'Brico Dépôt', 'Jeu de 4', 20),
('Vidage baignoire automatique chromé', 'Sanitaire', 'Baignoire', 'U', 65.00, 'Point P', 'Pièce', 20),
('Évier inox 1 bac 60x50 à encastrer', 'Sanitaire', 'Évier', 'U', 95.00, 'Brico Dépôt', 'Pièce', 20),
('Évier inox 2 bacs 116x50 à encastrer', 'Sanitaire', 'Évier', 'U', 165.00, 'Brico Dépôt', 'Pièce', 20),
('Évier granit composite 1 bac noir', 'Sanitaire', 'Évier', 'U', 265.00, 'Point P', 'Pièce', 20),
('Évier granit composite 2 bacs gris', 'Sanitaire', 'Évier', 'U', 385.00, 'Point P', 'Pièce', 20),
('Évier inox sous plan 1 bac', 'Sanitaire', 'Évier', 'U', 195.00, 'Point P', 'Pièce', 20),
('Cabine douche intégrale 90x90 verre', 'Sanitaire', 'Cabine', 'U', 680.00, 'Point P', 'Pièce', 20),
('Paroi douche fixe verre Sécurit 90cm', 'Sanitaire', 'Paroi', 'U', 245.00, 'Point P', 'Pièce', 20),
('Paroi douche pivotante verre 80cm', 'Sanitaire', 'Paroi', 'U', 285.00, 'Point P', 'Pièce', 20),
('Porte douche coulissante 120cm', 'Sanitaire', 'Paroi', 'U', 385.00, 'Point P', 'Pièce', 20),
('Bidet à poser céramique blanc', 'Sanitaire', 'Bidet', 'U', 145.00, 'Point P', 'Pièce', 20),
('Urinoir céramique blanc', 'Sanitaire', 'Urinoir', 'U', 195.00, 'Point P', 'Pièce', 20),
('Robinetterie urinoir temporisée', 'Sanitaire', 'Urinoir', 'U', 95.00, 'Point P', 'Pièce', 20),
('Lave-mains compact 35cm céramique', 'Sanitaire', 'Lavabo', 'U', 65.00, 'Brico Dépôt', 'Pièce', 20),

-- ═══ ÉLECTRICITÉ — 60 articles ═══
('Disjoncteur courbe C 16A 1P+N', 'Électricité', 'Disjoncteur', 'U', 13.00, 'Point P', 'Pièce', 20),
('Disjoncteur courbe C 20A 1P+N', 'Électricité', 'Disjoncteur', 'U', 14.00, 'Point P', 'Pièce', 20),
('Disjoncteur courbe C 32A 1P+N', 'Électricité', 'Disjoncteur', 'U', 18.00, 'Point P', 'Pièce', 20),
('Disjoncteur courbe D 16A 1P+N', 'Électricité', 'Disjoncteur', 'U', 22.00, 'Point P', 'Pièce', 20),
('Disjoncteur tétrapolaire 32A', 'Électricité', 'Disjoncteur', 'U', 65.00, 'Point P', 'Pièce', 20),
('Disjoncteur différentiel 30mA 40A type AC', 'Électricité', 'Différentiel', 'U', 55.00, 'Point P', 'Pièce', 20),
('Disjoncteur différentiel 30mA 63A type AC', 'Électricité', 'Différentiel', 'U', 78.00, 'Point P', 'Pièce', 20),
('Disjoncteur différentiel 30mA 40A type A', 'Électricité', 'Différentiel', 'U', 95.00, 'Point P', 'Pièce', 20),
('Différentiel type B pour borne IRVE 40A', 'Électricité', 'Différentiel', 'U', 285.00, 'Point P', 'Pièce', 20),
('Parafoudre type 2 monophasé 25kA', 'Électricité', 'Parafoudre', 'U', 125.00, 'Point P', 'Pièce', 20),
('Parafoudre type 2 triphasé 25kA', 'Électricité', 'Parafoudre', 'U', 195.00, 'Point P', 'Pièce', 20),
('Tableau électrique nu 13 modules 1 rangée', 'Électricité', 'Tableau', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Tableau électrique nu 26 modules 2 rangées', 'Électricité', 'Tableau', 'U', 65.00, 'Brico Dépôt', 'Pièce', 20),
('Tableau électrique pré-équipé 3 rangées', 'Électricité', 'Tableau', 'U', 285.00, 'Point P', 'Pièce', 20),
('Coffret communication grade 3 13 modules', 'Électricité', 'Tableau VDI', 'U', 145.00, 'Point P', 'Pièce', 20),
('Switch 8 ports gigabit pour coffret VDI', 'Électricité', 'Réseau', 'U', 68.00, 'Brico Dépôt', 'Pièce', 20),
('Patch panel RJ45 8 ports cat6', 'Électricité', 'Réseau', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Prise 2P+T 16A encastrée blanche', 'Électricité', 'Prise', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Prise 2P+T 16A double encastrée blanche', 'Électricité', 'Prise', 'U', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Prise 2P+T 16A étanche IP55 saillie', 'Électricité', 'Prise', 'U', 14.00, 'Brico Dépôt', 'Pièce', 20),
('Prise 32A 3P+T pour cuisinière', 'Électricité', 'Prise', 'U', 12.00, 'Brico Dépôt', 'Pièce', 20),
('Prise RJ45 cat6 encastrée blanche', 'Électricité', 'Prise réseau', 'U', 9.50, 'Brico Dépôt', 'Pièce', 20),
('Prise USB 2 ports + 2P+T encastrée', 'Électricité', 'Prise', 'U', 24.00, 'Point P', 'Pièce', 20),
('Prise TV/SAT/FM encastrée', 'Électricité', 'Prise TV', 'U', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Interrupteur va-et-vient encastré blanc', 'Électricité', 'Interrupteur', 'U', 3.80, 'Brico Dépôt', 'Pièce', 20),
('Interrupteur double va-et-vient encastré', 'Électricité', 'Interrupteur', 'U', 6.50, 'Brico Dépôt', 'Pièce', 20),
('Interrupteur poussoir lumineux encastré', 'Électricité', 'Interrupteur', 'U', 5.50, 'Brico Dépôt', 'Pièce', 20),
('Variateur d''éclairage rotatif LED', 'Électricité', 'Variateur', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Détecteur de mouvement encastré 360°', 'Électricité', 'Détecteur', 'U', 45.00, 'Brico Dépôt', 'Pièce', 20),
('Détecteur de présence couloir 180°', 'Électricité', 'Détecteur', 'U', 55.00, 'Point P', 'Pièce', 20),
('Câble U-1000 R2V 3G1.5 (par ml)', 'Électricité', 'Câble', 'ml', 1.80, 'Brico Dépôt', 'Couronne 50m', 20),
('Câble U-1000 R2V 3G2.5 (par ml)', 'Électricité', 'Câble', 'ml', 2.20, 'Brico Dépôt', 'Couronne 50m', 20),
('Câble U-1000 R2V 3G6 (par ml)', 'Électricité', 'Câble', 'ml', 4.50, 'Brico Dépôt', 'Couronne 50m', 20),
('Câble U-1000 R2V 3G10 (par ml)', 'Électricité', 'Câble', 'ml', 6.80, 'Point P', 'Couronne 50m', 20),
('Câble U-1000 R2V 5G6 (par ml)', 'Électricité', 'Câble', 'ml', 7.20, 'Point P', 'Couronne 50m', 20),
('Câble RJ45 cat6 U/UTP (par ml)', 'Électricité', 'Câble réseau', 'ml', 1.50, 'Brico Dépôt', 'Couronne 305m', 20),
('Câble RJ45 cat6a S/FTP (par ml)', 'Électricité', 'Câble réseau', 'ml', 2.80, 'Point P', 'Couronne 305m', 20),
('Câble coaxial TV 75 ohms (par ml)', 'Électricité', 'Câble', 'ml', 1.20, 'Brico Dépôt', 'Couronne 100m', 20),
('Gaine ICTA Ø16 grise 50m', 'Électricité', 'Gaine', 'U', 18.00, 'Brico Dépôt', 'Couronne 50m', 20),
('Gaine ICTA Ø20 grise 50m', 'Électricité', 'Gaine', 'U', 22.00, 'Brico Dépôt', 'Couronne 50m', 20),
('Gaine ICTA Ø25 grise 50m', 'Électricité', 'Gaine', 'U', 28.00, 'Brico Dépôt', 'Couronne 50m', 20),
('Gaine TPC Ø40 rouge 25m', 'Électricité', 'Gaine', 'U', 24.00, 'Point P', 'Couronne 25m', 20),
('Gaine TPC Ø63 verte 25m', 'Électricité', 'Gaine', 'U', 38.00, 'Point P', 'Couronne 25m', 20),
('Boîte d''encastrement Ø67 simple', 'Électricité', 'Boîte', 'U', 0.85, 'Brico Dépôt', 'Pièce', 20),
('Boîte d''encastrement Ø67 double', 'Électricité', 'Boîte', 'U', 1.50, 'Brico Dépôt', 'Pièce', 20),
('Boîte d''encastrement Ø67 triple', 'Électricité', 'Boîte', 'U', 2.20, 'Brico Dépôt', 'Pièce', 20),
('Boîte d''encastrement étanche IP55 simple', 'Électricité', 'Boîte', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Boîte de dérivation Ø80 placo', 'Électricité', 'Boîte', 'U', 1.80, 'Brico Dépôt', 'Pièce', 20),
('Domino 4mm² 12 plots', 'Électricité', 'Connexion', 'U', 1.20, 'Brico Dépôt', 'Pièce', 20),
('Wago 3 entrées (boîte 50)', 'Électricité', 'Connexion', 'boîte', 18.00, 'Brico Dépôt', 'Boîte 50', 20),
('Wago 5 entrées (boîte 50)', 'Électricité', 'Connexion', 'boîte', 24.00, 'Brico Dépôt', 'Boîte 50', 20),
('Spot LED encastré IP65 7W blanc neutre', 'Électricité', 'Éclairage', 'U', 14.00, 'Brico Dépôt', 'Pièce', 20),
('Spot LED encastré orientable 7W', 'Électricité', 'Éclairage', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Réglette LED 1m 18W', 'Électricité', 'Éclairage', 'U', 24.00, 'Brico Dépôt', 'Pièce', 20),
('Plafonnier LED rond 24W IP44', 'Électricité', 'Éclairage', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Bloc autonome BAES 60 lumens 1h', 'Électricité', 'Sécurité', 'U', 65.00, 'Point P', 'Pièce', 20),
('DAAF détecteur fumée NF EN 14604', 'Électricité', 'Sécurité', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Sonnette filaire carillon 230V', 'Électricité', 'Sonnerie', 'U', 24.00, 'Brico Dépôt', 'Pièce', 20),
('Visiophone 2 fils 7" couleur kit', 'Électricité', 'Visiophone', 'U', 285.00, 'Point P', 'Pièce', 20),
('Volet roulant motorisé filaire 230V (moteur)', 'Électricité', 'Volet', 'U', 95.00, 'Brico Dépôt', 'Pièce', 20),

-- ═══ CARRELAGE — 50 articles ═══
('Carrelage grès cérame 30x30 gris (m²)', 'Carrelage', 'Sol', 'm2', 14.50, 'Brico Dépôt', 'Carton 1.5m²', 20),
('Carrelage grès cérame 45x45 beige (m²)', 'Carrelage', 'Sol', 'm2', 18.00, 'Gedimat', 'Carton 1.5m²', 20),
('Carrelage grès cérame 60x60 gris clair (m²)', 'Carrelage', 'Sol', 'm2', 24.90, 'Gedimat', 'Carton 1.4m²', 20),
('Carrelage grès cérame 60x60 imitation pierre (m²)', 'Carrelage', 'Sol', 'm2', 28.50, 'Point P', 'Carton 1.4m²', 20),
('Carrelage grès cérame 80x80 effet béton (m²)', 'Carrelage', 'Sol', 'm2', 38.00, 'Point P', 'Carton 1.3m²', 20),
('Carrelage grand format 120x60 marbre (m²)', 'Carrelage', 'Sol', 'm2', 58.00, 'Point P', 'Carton 1.4m²', 20),
('Carrelage extérieur antidérapant R11 60x60 (m²)', 'Carrelage', 'Extérieur', 'm2', 32.00, 'Point P', 'Carton 1.4m²', 20),
('Carrelage extérieur 40x40 dalle terrasse (m²)', 'Carrelage', 'Extérieur', 'm2', 24.00, 'Brico Dépôt', 'Pièce', 20),
('Carrelage piscine antidérapant 25x25 bleu (m²)', 'Carrelage', 'Piscine', 'm2', 38.00, 'Point P', 'Carton 1m²', 20),
('Carrelage imitation parquet 20x120 chêne (m²)', 'Carrelage', 'Sol', 'm2', 32.00, 'Gedimat', 'Carton 1.4m²', 20),
('Faïence murale 25x40 blanc brillant (m²)', 'Carrelage', 'Mur', 'm2', 14.00, 'Brico Dépôt', 'Carton 1m²', 20),
('Faïence murale 30x60 gris perle (m²)', 'Carrelage', 'Mur', 'm2', 19.50, 'Gedimat', 'Carton 1.08m²', 20),
('Faïence métro 7.5x15 blanc brillant (m²)', 'Carrelage', 'Mur', 'm2', 22.00, 'Point P', 'Carton 0.9m²', 20),
('Faïence grand format 60x120 marbre (m²)', 'Carrelage', 'Mur', 'm2', 48.00, 'Point P', 'Carton 1.44m²', 20),
('Mosaïque pâte de verre 30x30 (m²)', 'Carrelage', 'Mosaïque', 'm2', 28.00, 'Point P', 'Plaque 30x30', 20),
('Mosaïque émaux 25x25 mix bleu (m²)', 'Carrelage', 'Mosaïque', 'm2', 38.00, 'Point P', 'Plaque', 20),
('Mosaïque marbre hexagonale (m²)', 'Carrelage', 'Mosaïque', 'm2', 65.00, 'Point P', 'Plaque', 20),
('Plinthe carrelage 8cm assortie (par ml)', 'Carrelage', 'Plinthe', 'ml', 5.50, 'Brico Dépôt', 'Pièce', 20),
('Plinthe carrelage gorge 10cm (par ml)', 'Carrelage', 'Plinthe', 'ml', 8.50, 'Point P', 'Pièce', 20),
('Listel décor 5x25 inox (par ml)', 'Carrelage', 'Décor', 'ml', 14.00, 'Point P', 'Pièce', 20),
('Frise marbre 5x30 (par ml)', 'Carrelage', 'Décor', 'ml', 18.00, 'Point P', 'Pièce', 20),
('Profilé alu jonction sol 25mm (par ml)', 'Carrelage', 'Profilé', 'ml', 4.80, 'Brico Dépôt', 'Barre 2.5m', 20),
('Profilé alu nez de marche antidérapant', 'Carrelage', 'Profilé', 'ml', 8.50, 'Point P', 'Pièce', 20),
('Profilé alu angle sortant 8mm', 'Carrelage', 'Profilé', 'ml', 4.20, 'Brico Dépôt', 'Pièce', 20),
('Mortier-colle C2 sac 25kg (intérieur)', 'Carrelage', 'Colle', 'sac', 14.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier-colle C2S1 flex sac 25kg', 'Carrelage', 'Colle', 'sac', 22.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier-colle C2ES1 immersion sac 25kg', 'Carrelage', 'Colle', 'sac', 28.00, 'Point P', 'Sac 25kg', 20),
('Colle blanche carreleur sac 25kg', 'Carrelage', 'Colle', 'sac', 12.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Joint ciment gris 25kg', 'Carrelage', 'Joint', 'sac', 14.50, 'Brico Dépôt', 'Sac 25kg', 20),
('Joint ciment blanc 25kg', 'Carrelage', 'Joint', 'sac', 16.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Joint époxy 5kg gris', 'Carrelage', 'Joint', 'sac', 38.00, 'Point P', 'Seau 5kg', 20),
('Joint époxy 5kg blanc', 'Carrelage', 'Joint', 'sac', 42.00, 'Point P', 'Seau 5kg', 20),
('Joint hydrofuge salle de bain 5kg', 'Carrelage', 'Joint', 'sac', 22.00, 'Brico Dépôt', 'Seau 5kg', 20),
('Mastic silicone sanitaire blanc 310ml', 'Carrelage', 'Étanchéité', 'U', 6.50, 'Brico Dépôt', 'Cartouche 310ml', 20),
('Mastic silicone sanitaire transparent 310ml', 'Carrelage', 'Étanchéité', 'U', 7.50, 'Brico Dépôt', 'Cartouche 310ml', 20),
('SEL système d''étanchéité liquide 7L', 'Carrelage', 'Étanchéité', 'U', 95.00, 'Point P', 'Bidon 7L', 20),
('Bande renfort SEL 10cm (rouleau 50m)', 'Carrelage', 'Étanchéité', 'U', 38.00, 'Point P', 'Rouleau 50m', 20),
('Primaire d''accrochage carrelage 5L', 'Carrelage', 'Préparation', 'U', 28.00, 'Brico Dépôt', 'Bidon 5L', 20),
('Ragréage P3 fibré 25kg auto-lissant', 'Carrelage', 'Préparation', 'sac', 18.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Ragréage extérieur fibré 25kg', 'Carrelage', 'Préparation', 'sac', 24.00, 'Point P', 'Sac 25kg', 20),
('Croisillon 2mm carreleur (sachet 250)', 'Carrelage', 'Outillage', 'sachet', 6.00, 'Brico Dépôt', 'Sachet 250', 20),
('Croisillon 3mm carreleur (sachet 250)', 'Carrelage', 'Outillage', 'sachet', 6.50, 'Brico Dépôt', 'Sachet 250', 20),
('Croisillon autonivelant 2mm (sachet 100)', 'Carrelage', 'Outillage', 'sachet', 14.00, 'Point P', 'Sachet 100', 20),
('Cale plastique sol 5mm (sachet 100)', 'Carrelage', 'Outillage', 'sachet', 4.50, 'Brico Dépôt', 'Sachet 100', 20),
('Margelle pierre reconstituée 30cm beige (par ml)', 'Carrelage', 'Margelle', 'ml', 18.00, 'Point P', 'Pièce', 20),
('Margelle pierre naturelle 32cm grise (par ml)', 'Carrelage', 'Margelle', 'ml', 38.00, 'Point P', 'Pièce', 20),
('Plot terrasse réglable 4-7cm (jeu 10)', 'Carrelage', 'Plot', 'jeu', 24.00, 'Brico Dépôt', 'Jeu 10', 20),
('Plot terrasse réglable 7-12cm (jeu 10)', 'Carrelage', 'Plot', 'jeu', 32.00, 'Brico Dépôt', 'Jeu 10', 20),
('Trame chauffante électrique 150W/m² (m²)', 'Carrelage', 'Plancher chauffant', 'm2', 48.00, 'Point P', 'Trame', 20),
('Pierre marbre travertin 60x40 beige (m²)', 'Carrelage', 'Pierre', 'm2', 65.00, 'Point P', 'Pièce', 20),

-- ═══ PEINTURE — 40 articles ═══
('Peinture acrylique mate blanche 10L', 'Peinture', 'Murs', 'U', 58.00, 'Brico Dépôt', 'Bidon 10L', 20),
('Peinture acrylique satinée blanche 10L', 'Peinture', 'Murs', 'U', 68.00, 'Brico Dépôt', 'Bidon 10L', 20),
('Peinture acrylique mate couleur 10L (RAL au choix)', 'Peinture', 'Murs', 'U', 78.00, 'Point P', 'Bidon 10L', 20),
('Peinture acrylique satinée couleur 10L', 'Peinture', 'Murs', 'U', 88.00, 'Point P', 'Bidon 10L', 20),
('Peinture acrylique velours blanche 10L premium', 'Peinture', 'Murs', 'U', 95.00, 'Point P', 'Bidon 10L', 20),
('Peinture monocouche blanc mat 10L', 'Peinture', 'Murs', 'U', 48.00, 'Brico Dépôt', 'Bidon 10L', 20),
('Peinture cuisine/salle de bain anti-condensation 5L', 'Peinture', 'Spéciale', 'U', 78.00, 'Point P', 'Bidon 5L', 20),
('Peinture façade pliolite blanche 10L', 'Peinture', 'Façade', 'U', 95.00, 'Point P', 'Bidon 10L', 20),
('Peinture façade silicate blanche 15L', 'Peinture', 'Façade', 'U', 145.00, 'Point P', 'Bidon 15L', 20),
('Peinture façade siloxane couleur 15L', 'Peinture', 'Façade', 'U', 165.00, 'Point P', 'Bidon 15L', 20),
('Peinture sol garage époxy 5L gris', 'Peinture', 'Sol', 'U', 78.00, 'Brico Dépôt', 'Bidon 5L', 20),
('Peinture sol antidérapante 5L', 'Peinture', 'Sol', 'U', 95.00, 'Point P', 'Bidon 5L', 20),
('Peinture radiateur blanc satin 750ml', 'Peinture', 'Métaux', 'U', 18.00, 'Brico Dépôt', 'Pot 750ml', 20),
('Peinture fer antirouille noir 2.5L', 'Peinture', 'Métaux', 'U', 38.00, 'Brico Dépôt', 'Pot 2.5L', 20),
('Peinture glycéro brillante blanche 2.5L', 'Peinture', 'Boiseries', 'U', 32.00, 'Brico Dépôt', 'Pot 2.5L', 20),
('Peinture glycéro satinée 2.5L', 'Peinture', 'Boiseries', 'U', 35.00, 'Brico Dépôt', 'Pot 2.5L', 20),
('Vernis bois polyuréthane 1L mat', 'Peinture', 'Boiseries', 'U', 24.00, 'Brico Dépôt', 'Pot 1L', 20),
('Lasure extérieure bois 5L incolore', 'Peinture', 'Boiseries', 'U', 38.00, 'Brico Dépôt', 'Bidon 5L', 20),
('Lasure extérieure bois 5L chêne moyen', 'Peinture', 'Boiseries', 'U', 42.00, 'Brico Dépôt', 'Bidon 5L', 20),
('Sous-couche universelle blanche 10L', 'Peinture', 'Préparation', 'U', 38.00, 'Brico Dépôt', 'Bidon 10L', 20),
('Sous-couche bois 2.5L', 'Peinture', 'Préparation', 'U', 22.00, 'Brico Dépôt', 'Pot 2.5L', 20),
('Sous-couche métaux 2.5L antirouille', 'Peinture', 'Préparation', 'U', 28.00, 'Brico Dépôt', 'Pot 2.5L', 20),
('Sous-couche fixateur murs poreux 10L', 'Peinture', 'Préparation', 'U', 42.00, 'Brico Dépôt', 'Bidon 10L', 20),
('Enduit lissage prêt à l''emploi 17kg', 'Peinture', 'Enduit', 'U', 22.00, 'Brico Dépôt', 'Seau 17kg', 20),
('Enduit garnissant poudre 25kg', 'Peinture', 'Enduit', 'sac', 16.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Enduit de rebouchage 1kg', 'Peinture', 'Enduit', 'U', 6.50, 'Brico Dépôt', 'Pot 1kg', 20),
('Décapant peinture gel 1L', 'Peinture', 'Préparation', 'U', 18.00, 'Brico Dépôt', 'Pot 1L', 20),
('Lessive ST Marc 1kg', 'Peinture', 'Préparation', 'U', 5.50, 'Brico Dépôt', 'Boîte 1kg', 20),
('Bâche plastique transparente 4x5m', 'Peinture', 'Protection', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Bâche plastique armée 5x10m', 'Peinture', 'Protection', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Adhésif de masquage 38mm 50m', 'Peinture', 'Protection', 'U', 4.50, 'Brico Dépôt', 'Rouleau', 20),
('Adhésif de masquage haute qualité 50mm 50m', 'Peinture', 'Protection', 'U', 8.50, 'Brico Dépôt', 'Rouleau', 20),
('Pinceau plat 30mm haute qualité', 'Peinture', 'Outillage', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Pinceau plat 60mm haute qualité', 'Peinture', 'Outillage', 'U', 7.50, 'Brico Dépôt', 'Pièce', 20),
('Pinceau brosse à rechampir Ø35', 'Peinture', 'Outillage', 'U', 5.50, 'Brico Dépôt', 'Pièce', 20),
('Rouleau microfibre 18cm + manche', 'Peinture', 'Outillage', 'U', 6.50, 'Brico Dépôt', 'Pièce', 20),
('Rouleau laqueur 11cm + manche', 'Peinture', 'Outillage', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Bac à peinture + grille essorage', 'Peinture', 'Outillage', 'U', 5.80, 'Brico Dépôt', 'Pièce', 20),
('Toile non-tissée 1x10m unie', 'Peinture', 'Décor', 'U', 24.00, 'Point P', 'Rouleau 10m', 20),
('Papier peint vinyle expansé rouleau 10m', 'Peinture', 'Décor', 'U', 32.00, 'Brico Dépôt', 'Rouleau 10m', 20),

-- ═══ PLÂTRERIE — 50 articles ═══
('BA13 standard 250x120cm 12.5mm', 'Plâtrerie', 'BA13', 'plaque', 5.50, 'Brico Dépôt', 'Plaque', 20),
('BA13 standard 300x120cm 12.5mm', 'Plâtrerie', 'BA13', 'plaque', 6.80, 'Brico Dépôt', 'Plaque', 20),
('BA13 hydrofuge 250x120cm vert', 'Plâtrerie', 'BA13', 'plaque', 8.50, 'Brico Dépôt', 'Plaque', 20),
('BA13 hydrofuge 300x120cm vert', 'Plâtrerie', 'BA13', 'plaque', 10.50, 'Brico Dépôt', 'Plaque', 20),
('BA13 coupe-feu 250x120cm rose', 'Plâtrerie', 'BA13', 'plaque', 9.50, 'Point P', 'Plaque', 20),
('BA15 coupe-feu 250x120cm rose', 'Plâtrerie', 'BA15', 'plaque', 14.00, 'Point P', 'Plaque', 20),
('BA18 hydrofuge 250x120cm vert renforcé', 'Plâtrerie', 'BA18', 'plaque', 16.00, 'Point P', 'Plaque', 20),
('BA13 acoustique 250x120cm bleu', 'Plâtrerie', 'BA13', 'plaque', 12.00, 'Point P', 'Plaque', 20),
('Fermacell fibre-gypse 250x120cm 12.5mm', 'Plâtrerie', 'Fermacell', 'plaque', 22.00, 'Point P', 'Plaque', 20),
('Plaque polystyrène doublage 80mm 250x120', 'Plâtrerie', 'Doublage', 'plaque', 18.00, 'Brico Dépôt', 'Plaque', 20),
('Plaque polystyrène doublage 100mm 250x120', 'Plâtrerie', 'Doublage', 'plaque', 22.00, 'Brico Dépôt', 'Plaque', 20),
('Doublage Placomur 13+80 (m²)', 'Plâtrerie', 'Doublage', 'm2', 14.50, 'Point P', 'Plaque 250x120', 20),
('Doublage Placomur 13+100 (m²)', 'Plâtrerie', 'Doublage', 'm2', 16.50, 'Point P', 'Plaque 250x120', 20),
('Rail M48 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 4.50, 'Brico Dépôt', 'Barre 3m', 20),
('Rail M70 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 6.50, 'Brico Dépôt', 'Barre 3m', 20),
('Rail M100 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 8.50, 'Point P', 'Barre 3m', 20),
('Montant M48 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 4.20, 'Brico Dépôt', 'Barre 3m', 20),
('Montant M70 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 6.20, 'Brico Dépôt', 'Barre 3m', 20),
('Montant M100 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 8.20, 'Point P', 'Barre 3m', 20),
('Fourrure F530 longueur 3m', 'Plâtrerie', 'Ossature', 'U', 3.80, 'Brico Dépôt', 'Barre 3m', 20),
('Suspente longue tige Ø6mm pour faux plafond', 'Plâtrerie', 'Ossature', 'U', 0.85, 'Brico Dépôt', 'Pièce', 20),
('Suspente acoustique anti-vibratoire', 'Plâtrerie', 'Ossature', 'U', 4.50, 'Point P', 'Pièce', 20),
('Cornière d''angle perforée alu 3m', 'Plâtrerie', 'Profilé', 'U', 4.50, 'Brico Dépôt', 'Barre 3m', 20),
('Cornière d''angle PVC 3m', 'Plâtrerie', 'Profilé', 'U', 3.20, 'Brico Dépôt', 'Barre 3m', 20),
('Vis TTPC 25mm boîte 1000', 'Plâtrerie', 'Visserie', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 1000', 20),
('Vis TTPC 35mm boîte 1000', 'Plâtrerie', 'Visserie', 'boîte', 16.00, 'Brico Dépôt', 'Boîte 1000', 20),
('Vis TTPC 45mm boîte 1000', 'Plâtrerie', 'Visserie', 'boîte', 18.00, 'Brico Dépôt', 'Boîte 1000', 20),
('Vis TTPC 55mm boîte 500', 'Plâtrerie', 'Visserie', 'boîte', 16.00, 'Brico Dépôt', 'Boîte 500', 20),
('Cheville Molly 4x46 boîte 100', 'Plâtrerie', 'Cheville', 'boîte', 12.00, 'Brico Dépôt', 'Boîte 100', 20),
('Cheville Molly 6x52 boîte 50', 'Plâtrerie', 'Cheville', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 50', 20),
('Cheville BA13 universelle (boîte 100)', 'Plâtrerie', 'Cheville', 'boîte', 8.50, 'Brico Dépôt', 'Boîte 100', 20),
('Bande à joint papier 150m', 'Plâtrerie', 'Joint', 'U', 8.50, 'Brico Dépôt', 'Rouleau 150m', 20),
('Bande à joint fibre adhésive 90m', 'Plâtrerie', 'Joint', 'U', 14.00, 'Brico Dépôt', 'Rouleau 90m', 20),
('Bande armée d''angle alu/papier 30m', 'Plâtrerie', 'Joint', 'U', 18.00, 'Point P', 'Rouleau 30m', 20),
('Enduit joint poudre 25kg standard', 'Plâtrerie', 'Enduit', 'sac', 12.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Enduit joint prêt à l''emploi 25kg', 'Plâtrerie', 'Enduit', 'seau', 18.00, 'Brico Dépôt', 'Seau 25kg', 20),
('Enduit joint allégé prêt à l''emploi 17L', 'Plâtrerie', 'Enduit', 'seau', 24.00, 'Point P', 'Seau 17L', 20),
('MAP plâtre-colle 25kg', 'Plâtrerie', 'Plâtre', 'sac', 12.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Plâtre fin 40kg', 'Plâtrerie', 'Plâtre', 'sac', 8.50, 'Brico Dépôt', 'Sac 40kg', 20),
('Plâtre traditionnel 25kg', 'Plâtrerie', 'Plâtre', 'sac', 7.50, 'Brico Dépôt', 'Sac 25kg', 20),
('Bande désolidarisation périphérique 50mm', 'Plâtrerie', 'Acoustique', 'ml', 0.85, 'Point P', 'Rouleau 50m', 20),
('Trappe de visite alu BA13 60x60', 'Plâtrerie', 'Trappe', 'U', 62.00, 'Point P', 'Pièce', 20),
('Trappe de visite alu BA13 30x30', 'Plâtrerie', 'Trappe', 'U', 38.00, 'Point P', 'Pièce', 20),
('Brique plâtrière 50mm (m²)', 'Plâtrerie', 'Brique', 'm2', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Carreau de plâtre standard 66x50x7 (m²)', 'Plâtrerie', 'Carreau', 'm2', 14.00, 'Point P', 'Pièce', 20),
('Carreau de plâtre hydro 66x50x7 (m²)', 'Plâtrerie', 'Carreau', 'm2', 18.00, 'Point P', 'Pièce', 20),
('Corniche plâtre staff 12cm (par ml)', 'Plâtrerie', 'Décor', 'ml', 18.00, 'Point P', 'Pièce', 20),
('Rosace plâtre Ø60', 'Plâtrerie', 'Décor', 'U', 55.00, 'Point P', 'Pièce', 20),
('Frein-vapeur Sd18 rouleau 75m²', 'Plâtrerie', 'Étanchéité air', 'U', 165.00, 'Point P', 'Rouleau 75m²', 20),
('Adhésif joints frein-vapeur 25m', 'Plâtrerie', 'Étanchéité air', 'U', 14.00, 'Point P', 'Rouleau 25m', 20),

-- ═══ ISOLATION — 30 articles ═══
('Laine de verre 100mm rouleau 6m² R=2.5', 'Isolation', 'Laine de verre', 'm2', 6.50, 'Brico Dépôt', 'Rouleau 6m²', 20),
('Laine de verre 120mm rouleau 5m² R=3.0', 'Isolation', 'Laine de verre', 'm2', 7.50, 'Brico Dépôt', 'Rouleau 5m²', 20),
('Laine de verre 200mm rouleau 4m² R=5.0', 'Isolation', 'Laine de verre', 'm2', 11.00, 'Brico Dépôt', 'Rouleau 4m²', 20),
('Laine de verre 240mm rouleau 4m² R=6.0', 'Isolation', 'Laine de verre', 'm2', 13.00, 'Point P', 'Rouleau 4m²', 20),
('Laine de verre soufflée vrac sac 16kg', 'Isolation', 'Laine de verre', 'sac', 28.00, 'Point P', 'Sac 16kg', 20),
('Laine de roche 100mm rouleau 5m²', 'Isolation', 'Laine de roche', 'm2', 8.50, 'Brico Dépôt', 'Rouleau 5m²', 20),
('Laine de roche 140mm rouleau 4m² R=3.5', 'Isolation', 'Laine de roche', 'm2', 11.00, 'Brico Dépôt', 'Rouleau 4m²', 20),
('Laine de roche 200mm rouleau 3m² R=5.0', 'Isolation', 'Laine de roche', 'm2', 13.00, 'Point P', 'Rouleau 3m²', 20),
('Panneau laine de roche HD 45mm 60x120', 'Isolation', 'Laine de roche', 'plaque', 12.00, 'Point P', 'Plaque', 20),
('Panneau laine de roche HD 100mm 60x120', 'Isolation', 'Laine de roche', 'plaque', 18.00, 'Point P', 'Plaque', 20),
('Polystyrène expansé 60mm 100x50 R=1.55', 'Isolation', 'Polystyrène', 'plaque', 4.50, 'Brico Dépôt', 'Plaque 0.5m²', 20),
('Polystyrène expansé 100mm 100x50 R=2.6', 'Isolation', 'Polystyrène', 'plaque', 7.50, 'Brico Dépôt', 'Plaque 0.5m²', 20),
('Polystyrène expansé 140mm 100x50 R=3.65', 'Isolation', 'Polystyrène', 'plaque', 10.50, 'Brico Dépôt', 'Plaque 0.5m²', 20),
('Polystyrène extrudé XPS 60mm 125x60', 'Isolation', 'Polystyrène', 'plaque', 14.00, 'Point P', 'Plaque', 20),
('Polystyrène extrudé XPS 100mm 125x60', 'Isolation', 'Polystyrène', 'plaque', 22.00, 'Point P', 'Plaque', 20),
('Polyuréthane PIR 60mm 120x60 R=2.7', 'Isolation', 'PIR', 'plaque', 16.00, 'Point P', 'Plaque', 20),
('Polyuréthane PIR 80mm 120x60 R=3.6', 'Isolation', 'PIR', 'plaque', 22.00, 'Point P', 'Plaque', 20),
('Polyuréthane PIR 100mm 120x60 R=4.5', 'Isolation', 'PIR', 'plaque', 28.00, 'Point P', 'Plaque', 20),
('Pare-vapeur kraft armé rouleau 75m²', 'Isolation', 'Pare-vapeur', 'U', 38.00, 'Point P', 'Rouleau 75m²', 20),
('Frein-vapeur hygrovariable Sd0.25-25 75m²', 'Isolation', 'Frein-vapeur', 'U', 195.00, 'Point P', 'Rouleau 75m²', 20),
('Pare-pluie HPV 75m²', 'Isolation', 'Pare-pluie', 'U', 95.00, 'Point P', 'Rouleau 75m²', 20),
('Multicouche réflecteur 25mm rouleau 6m²', 'Isolation', 'Multicouche', 'm2', 18.00, 'Point P', 'Rouleau 6m²', 20),
('Ouate de cellulose vrac sac 12kg', 'Isolation', 'Ouate cellulose', 'sac', 18.00, 'Point P', 'Sac 12kg', 20),
('Liège expansé naturel 40mm 100x50', 'Isolation', 'Naturel', 'plaque', 28.00, 'Point P', 'Plaque', 20),
('Fibre de bois rigide 60mm 130x60', 'Isolation', 'Naturel', 'plaque', 22.00, 'Point P', 'Plaque', 20),
('Chanvre vrac sac 10kg', 'Isolation', 'Naturel', 'sac', 24.00, 'Point P', 'Sac 10kg', 20),
('Bande adhésive butyl pare-vapeur 25m', 'Isolation', 'Étanchéité air', 'U', 18.00, 'Point P', 'Rouleau 25m', 20),
('Cheville à frapper isolant 90mm (boîte 100)', 'Isolation', 'Fixation', 'boîte', 18.00, 'Point P', 'Boîte 100', 20),
('Cheville à frapper isolant 140mm (boîte 100)', 'Isolation', 'Fixation', 'boîte', 24.00, 'Point P', 'Boîte 100', 20),
('Mousse PU expansive coupe-feu 750ml', 'Isolation', 'Étanchéité', 'U', 14.00, 'Brico Dépôt', 'Aérosol 750ml', 20),

-- ═══ MENUISERIE — 40 articles ═══
('Bloc-porte intérieur âme alvéolaire 83x204 prépeinte', 'Menuiserie', 'Porte int', 'U', 95.00, 'Brico Dépôt', 'Pièce', 20),
('Bloc-porte intérieur âme pleine 83x204 laquée', 'Menuiserie', 'Porte int', 'U', 165.00, 'Point P', 'Pièce', 20),
('Bloc-porte CF 30 minutes 83x204', 'Menuiserie', 'Porte int', 'U', 385.00, 'Point P', 'Pièce', 20),
('Bloc-porte palière acoustique 32dB 83x204', 'Menuiserie', 'Porte int', 'U', 520.00, 'Point P', 'Pièce', 20),
('Bloc-porte cave isoplane 83x204', 'Menuiserie', 'Porte int', 'U', 125.00, 'Brico Dépôt', 'Pièce', 20),
('Bloc-porte vitrée 4 carreaux 83x204', 'Menuiserie', 'Porte int', 'U', 385.00, 'Point P', 'Pièce', 20),
('Châssis galandage simple 83x204', 'Menuiserie', 'Coulissant', 'U', 220.00, 'Point P', 'Pièce', 20),
('Système coulissant rail apparent 200cm', 'Menuiserie', 'Coulissant', 'U', 95.00, 'Brico Dépôt', 'Kit', 20),
('Trappe escamotable combles isolée 60x130', 'Menuiserie', 'Trappe', 'U', 145.00, 'Point P', 'Pièce', 20),
('Plinthe MDF 70mm prépeinte (par ml)', 'Menuiserie', 'Plinthe', 'ml', 4.50, 'Brico Dépôt', 'Barre 2.4m', 20),
('Plinthe MDF 100mm prépeinte (par ml)', 'Menuiserie', 'Plinthe', 'ml', 6.50, 'Brico Dépôt', 'Barre 2.4m', 20),
('Plinthe massif chêne 80mm (par ml)', 'Menuiserie', 'Plinthe', 'ml', 14.00, 'Point P', 'Barre 2.5m', 20),
('Quart-de-rond MDF 14x14 (par ml)', 'Menuiserie', 'Profilé', 'ml', 2.50, 'Brico Dépôt', 'Barre 2.4m', 20),
('Baguette d''angle MDF 25x25 (par ml)', 'Menuiserie', 'Profilé', 'ml', 3.50, 'Brico Dépôt', 'Barre 2.4m', 20),
('Cimaise MDF 60mm (par ml)', 'Menuiserie', 'Profilé', 'ml', 5.50, 'Point P', 'Barre 2.4m', 20),
('Joint d''isolation EPDM porte 7mm 100m', 'Menuiserie', 'Joint', 'U', 18.00, 'Brico Dépôt', 'Rouleau 100m', 20),
('Joint mousse adhésif fenêtre 10m', 'Menuiserie', 'Joint', 'U', 4.50, 'Brico Dépôt', 'Rouleau 10m', 20),
('Joint silicone polymère MS 290ml', 'Menuiserie', 'Joint', 'U', 8.50, 'Brico Dépôt', 'Cartouche', 20),
('Paumelle picarde 140mm (paire)', 'Menuiserie', 'Quincaillerie', 'paire', 6.50, 'Brico Dépôt', 'Paire', 20),
('Paumelle invisible Anuba 13x90', 'Menuiserie', 'Quincaillerie', 'U', 8.50, 'Point P', 'Pièce', 20),
('Charnière inox 80x80mm', 'Menuiserie', 'Quincaillerie', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Serrure encastrée bec de cane 50mm', 'Menuiserie', 'Serrure', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Serrure 3 points cylindre Européen', 'Menuiserie', 'Serrure', 'U', 195.00, 'Point P', 'Pièce', 20),
('Serrure 5 points A2P* certifiée', 'Menuiserie', 'Serrure', 'U', 285.00, 'Point P', 'Pièce', 20),
('Cylindre Européen 30x30 nickelé', 'Menuiserie', 'Serrure', 'U', 24.00, 'Brico Dépôt', 'Pièce', 20),
('Cylindre haute sécurité Bricard A2P**', 'Menuiserie', 'Serrure', 'U', 145.00, 'Point P', 'Pièce', 20),
('Poignée de porte béquille double inox', 'Menuiserie', 'Poignée', 'U', 28.00, 'Brico Dépôt', 'Paire', 20),
('Poignée de porte design noir mat', 'Menuiserie', 'Poignée', 'U', 65.00, 'Point P', 'Paire', 20),
('Bouton poussoir laiton chromé', 'Menuiserie', 'Poignée', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Tablette d''appui fenêtre PVC blanc 30cm (ml)', 'Menuiserie', 'Tablette', 'ml', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Tablette d''appui fenêtre MDF laqué 25cm (ml)', 'Menuiserie', 'Tablette', 'ml', 12.00, 'Point P', 'Pièce', 20),
('Étagère mélaminé blanc 200x40cm 19mm', 'Menuiserie', 'Étagère', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Étagère chêne massif 200x30cm 25mm', 'Menuiserie', 'Étagère', 'U', 65.00, 'Point P', 'Pièce', 20),
('Tasseau pin sapin 27x40 (par ml)', 'Menuiserie', 'Bois', 'ml', 1.20, 'Brico Dépôt', 'Barre 2.4m', 20),
('Tasseau douglas traité 22x95 (par ml)', 'Menuiserie', 'Bois', 'ml', 4.50, 'Point P', 'Barre 4m', 20),
('Lambris pin sapin RL 12mm (m²)', 'Menuiserie', 'Lambris', 'm2', 16.00, 'Brico Dépôt', 'Bottillon', 20),
('Lambris MDF laqué blanc 12mm (m²)', 'Menuiserie', 'Lambris', 'm2', 24.00, 'Point P', 'Pack', 20),
('Frisette pin lambourdage 90x18mm (m²)', 'Menuiserie', 'Lambris', 'm2', 14.00, 'Brico Dépôt', 'Bottillon', 20),
('Volige bois 18mm 100x250 (par m²)', 'Menuiserie', 'Bois', 'm2', 12.00, 'Point P', 'Pièce', 20),
('Solive douglas traité 75x220 (par ml)', 'Menuiserie', 'Bois', 'ml', 12.50, 'Point P', 'Barre 6m', 20),

-- ═══ COUVERTURE — 30 articles ═══
('Tuile mécanique terre cuite rouge (m²)', 'Couverture', 'Tuile', 'm2', 16.00, 'Point P', 'Palette', 20),
('Tuile mécanique grand moule terre cuite (m²)', 'Couverture', 'Tuile', 'm2', 18.00, 'Point P', 'Palette', 20),
('Tuile romane terre cuite (m²)', 'Couverture', 'Tuile', 'm2', 22.00, 'Point P', 'Palette', 20),
('Tuile canal terre cuite (m²)', 'Couverture', 'Tuile', 'm2', 24.00, 'Point P', 'Palette', 20),
('Tuile plate terre cuite (m²)', 'Couverture', 'Tuile', 'm2', 24.00, 'Point P', 'Palette', 20),
('Tuile béton standard (m²)', 'Couverture', 'Tuile', 'm2', 12.00, 'Brico Dépôt', 'Palette', 20),
('Faîtière demi-ronde tuile (par ml)', 'Couverture', 'Faîtage', 'ml', 14.00, 'Point P', 'Pièce', 20),
('Faîtière conique terre cuite (par U)', 'Couverture', 'Faîtage', 'U', 4.50, 'Point P', 'Pièce', 20),
('Closoir ventilé alu 5m', 'Couverture', 'Faîtage', 'U', 32.00, 'Point P', 'Rouleau 5m', 20),
('Bandeau de rive PVC 16cm (par ml)', 'Couverture', 'Rive', 'ml', 8.50, 'Brico Dépôt', 'Barre 5m', 20),
('Planche de rive bois sapin 25mm 200x16 (par ml)', 'Couverture', 'Rive', 'ml', 6.50, 'Point P', 'Barre 4m', 20),
('Ardoise naturelle 32x22 (m²)', 'Couverture', 'Ardoise', 'm2', 42.00, 'Point P', 'Palette', 20),
('Ardoise synthétique 32x22 (m²)', 'Couverture', 'Ardoise', 'm2', 28.00, 'Point P', 'Palette', 20),
('Crochet ardoise inox (boîte 100)', 'Couverture', 'Fixation', 'boîte', 28.00, 'Point P', 'Boîte 100', 20),
('Bac acier prélaqué 6m (m²)', 'Couverture', 'Bac acier', 'm2', 18.00, 'Point P', 'Bac 6m', 20),
('Panneau sandwich PIR 90mm prélaqué (m²)', 'Couverture', 'Panneau', 'm2', 48.00, 'Point P', 'Panneau', 20),
('Zinc-titane VMZ 0.65mm naturel (m²)', 'Couverture', 'Zinc', 'm2', 55.00, 'Point P', 'Plaque', 20),
('Zinc plié noue/solin (par ml)', 'Couverture', 'Zinc', 'ml', 16.00, 'Point P', 'Pièce', 20),
('Bavette plomb 2.5kg/m² rouleau 50cm (par ml)', 'Couverture', 'Plomb', 'ml', 6.00, 'Point P', 'Rouleau', 20),
('Gouttière demi-ronde zinc Ø125 (par ml)', 'Couverture', 'Gouttière', 'ml', 14.00, 'Point P', 'Barre 4m', 20),
('Gouttière demi-ronde PVC Ø125 (par ml)', 'Couverture', 'Gouttière', 'ml', 8.50, 'Brico Dépôt', 'Barre 4m', 20),
('Crochet zinc gouttière (la pièce)', 'Couverture', 'Gouttière', 'U', 2.50, 'Brico Dépôt', 'Pièce', 20),
('Naissance PVC zinc Ø125/80 départ', 'Couverture', 'Gouttière', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Tube de descente PVC Ø80 (par ml)', 'Couverture', 'Descente', 'ml', 6.50, 'Brico Dépôt', 'Barre 4m', 20),
('Tube de descente zinc Ø80 (par ml)', 'Couverture', 'Descente', 'ml', 11.00, 'Point P', 'Barre 2m', 20),
('Dauphin fonte Ø80 départ pied', 'Couverture', 'Descente', 'U', 38.00, 'Point P', 'Pièce', 20),
('Velux GGL CK06 78x118 confort blanc', 'Couverture', 'Velux', 'U', 475.00, 'Point P', 'Pièce', 20),
('Velux GGL MK06 78x118 motorisé', 'Couverture', 'Velux', 'U', 685.00, 'Point P', 'Pièce', 20),
('Raccord Velux EDW pour tuiles', 'Couverture', 'Velux', 'U', 95.00, 'Point P', 'Pièce', 20),
('Tuile à douille Ø125 ventilation', 'Couverture', 'Ventilation', 'U', 65.00, 'Point P', 'Pièce', 20),

-- ═══ MAÇONNERIE — 40 articles ═══
('Béton prêt à l''emploi C25/30 (m³)', 'Maçonnerie', 'Béton', 'm3', 125.00, 'Point P', 'Camion-toupie', 20),
('Béton fibré C25/30 (m³)', 'Maçonnerie', 'Béton', 'm3', 135.00, 'Point P', 'Camion-toupie', 20),
('Béton C30/37 hydrofuge (m³)', 'Maçonnerie', 'Béton', 'm3', 145.00, 'Point P', 'Camion-toupie', 20),
('Mortier prêt à l''emploi sac 25kg', 'Maçonnerie', 'Mortier', 'sac', 6.50, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier de chape sac 25kg', 'Maçonnerie', 'Mortier', 'sac', 7.50, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier-colle multi-supports sac 25kg', 'Maçonnerie', 'Mortier', 'sac', 12.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier de jointoiement chaux 25kg', 'Maçonnerie', 'Mortier', 'sac', 14.00, 'Point P', 'Sac 25kg', 20),
('Ciment Portland CEM II 32.5R sac 35kg', 'Maçonnerie', 'Ciment', 'sac', 9.50, 'Brico Dépôt', 'Sac 35kg', 20),
('Ciment blanc CEM II 32.5R sac 25kg', 'Maçonnerie', 'Ciment', 'sac', 16.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Chaux hydraulique NHL 3.5 sac 25kg', 'Maçonnerie', 'Chaux', 'sac', 14.00, 'Point P', 'Sac 25kg', 20),
('Chaux aérienne CL90 sac 25kg', 'Maçonnerie', 'Chaux', 'sac', 12.00, 'Point P', 'Sac 25kg', 20),
('Sable rivière 0/4 sac 35kg', 'Maçonnerie', 'Granulat', 'sac', 4.50, 'Brico Dépôt', 'Sac 35kg', 20),
('Sable rivière 0/4 (m³)', 'Maçonnerie', 'Granulat', 'm3', 42.00, 'Point P', 'Big bag', 20),
('Gravier 4/10 (m³)', 'Maçonnerie', 'Granulat', 'm3', 38.00, 'Point P', 'Big bag', 20),
('Gravier 6/14 (m³)', 'Maçonnerie', 'Granulat', 'm3', 38.00, 'Point P', 'Big bag', 20),
('GNT 0/31.5 (m³)', 'Maçonnerie', 'Granulat', 'm3', 18.00, 'Point P', 'Camion', 20),
('Parpaing creux 20x20x50 (la pièce)', 'Maçonnerie', 'Bloc', 'U', 1.40, 'Brico Dépôt', 'Palette 60', 20),
('Parpaing creux 15x20x50 (la pièce)', 'Maçonnerie', 'Bloc', 'U', 1.05, 'Brico Dépôt', 'Palette 80', 20),
('Parpaing creux 10x20x50 (la pièce)', 'Maçonnerie', 'Bloc', 'U', 0.85, 'Brico Dépôt', 'Palette 96', 20),
('Bloc béton creux 50x20x20 (la pièce)', 'Maçonnerie', 'Bloc', 'U', 1.85, 'Brico Dépôt', 'Palette 60', 20),
('Brique creuse 7cm 50x20 (la pièce)', 'Maçonnerie', 'Brique', 'U', 0.65, 'Point P', 'Palette', 20),
('Brique Monomur 20cm (m²)', 'Maçonnerie', 'Brique', 'm2', 38.00, 'Point P', 'Palette', 20),
('Brique foraine pleine rouge (la pièce)', 'Maçonnerie', 'Brique', 'U', 0.85, 'Point P', 'Palette', 20),
('Linteau béton précontraint 14x20 (par ml)', 'Maçonnerie', 'Linteau', 'ml', 24.00, 'Point P', 'Pièce', 20),
('Treillis soudé ST25C 6x2.4m (m²)', 'Maçonnerie', 'Acier', 'm2', 4.50, 'Brico Dépôt', 'Panneau 14.4m²', 20),
('Treillis soudé ST10C 6x2.4m (m²)', 'Maçonnerie', 'Acier', 'm2', 3.20, 'Brico Dépôt', 'Panneau 14.4m²', 20),
('Acier HA10 12m (par ml)', 'Maçonnerie', 'Acier', 'ml', 1.20, 'Brico Dépôt', 'Barre 12m', 20),
('Acier HA12 12m (par ml)', 'Maçonnerie', 'Acier', 'ml', 1.80, 'Brico Dépôt', 'Barre 12m', 20),
('Cadre HA8 100x100 (par U)', 'Maçonnerie', 'Acier', 'U', 1.50, 'Point P', 'Pièce', 20),
('Hourdis béton 12cm (la pièce)', 'Maçonnerie', 'Plancher', 'U', 4.50, 'Point P', 'Palette', 20),
('Hourdis polystyrène isolant 16cm (la pièce)', 'Maçonnerie', 'Plancher', 'U', 14.00, 'Point P', 'Pièce', 20),
('Poutrelle béton précontrainte 5m (la pièce)', 'Maçonnerie', 'Plancher', 'U', 38.00, 'Point P', 'Pièce', 20),
('Polyane film polyéthylène 200µ (m²)', 'Maçonnerie', 'Étanchéité', 'm2', 1.20, 'Brico Dépôt', 'Rouleau 25m', 20),
('Plaquettes parement pierre naturelle (m²)', 'Maçonnerie', 'Parement', 'm2', 65.00, 'Point P', 'Carton', 20),
('Briquettes parement terre cuite (m²)', 'Maçonnerie', 'Parement', 'm2', 42.00, 'Point P', 'Carton', 20),
('Mortier réparation béton 25kg', 'Maçonnerie', 'Mortier', 'sac', 18.00, 'Brico Dépôt', 'Sac 25kg', 20),
('Mortier de cuvelage hydrofuge 25kg', 'Maçonnerie', 'Étanchéité', 'sac', 22.00, 'Point P', 'Sac 25kg', 20),
('Adjuvant hydrofuge masse béton 5L', 'Maçonnerie', 'Adjuvant', 'U', 28.00, 'Point P', 'Bidon 5L', 20),
('Plastifiant béton 5L', 'Maçonnerie', 'Adjuvant', 'U', 24.00, 'Point P', 'Bidon 5L', 20),
('Liant ciment-chaux NHL2 sac 25kg', 'Maçonnerie', 'Mortier', 'sac', 18.00, 'Point P', 'Sac 25kg', 20),

-- ═══ ÉTANCHÉITÉ — 20 articles ═══
('Membrane EPDM 1.5mm rouleau 6x20m', 'Étanchéité', 'Membrane', 'm2', 28.00, 'Point P', 'Rouleau', 20),
('Membrane bitume APP 4mm rouleau 10m²', 'Étanchéité', 'Membrane', 'm2', 18.00, 'Point P', 'Rouleau 10m²', 20),
('Membrane bitume bicouche SBS 4mm 10m²', 'Étanchéité', 'Membrane', 'm2', 18.00, 'Point P', 'Rouleau 10m²', 20),
('Membrane PVC armée 1.5mm (m²)', 'Étanchéité', 'Membrane', 'm2', 24.00, 'Point P', 'Rouleau', 20),
('Membrane TPO 1.5mm (m²)', 'Étanchéité', 'Membrane', 'm2', 26.00, 'Point P', 'Rouleau', 20),
('Colle néoprène pour EPDM 5L', 'Étanchéité', 'Colle', 'U', 65.00, 'Point P', 'Bidon 5L', 20),
('Primaire d''accrochage bitume 25L', 'Étanchéité', 'Primaire', 'U', 78.00, 'Point P', 'Bidon 25L', 20),
('Bavette plomb 2.5kg/m² (par m²)', 'Étanchéité', 'Bavette', 'm2', 42.00, 'Point P', 'Rouleau 1m', 20),
('Joint dilatation EPDM 200mm (par ml)', 'Étanchéité', 'Joint', 'ml', 18.00, 'Point P', 'Rouleau', 20),
('Mastic-colle MS polymère 290ml (cartouche)', 'Étanchéité', 'Mastic', 'U', 12.00, 'Brico Dépôt', 'Cartouche 290ml', 20),
('Mastic acrylique extérieur 310ml', 'Étanchéité', 'Mastic', 'U', 5.50, 'Brico Dépôt', 'Cartouche 310ml', 20),
('Mastic polyuréthane 600ml poche', 'Étanchéité', 'Mastic', 'U', 14.00, 'Point P', 'Poche 600ml', 20),
('Naissance siphonée EP Ø80', 'Étanchéité', 'Évacuation', 'U', 95.00, 'Point P', 'Pièce', 20),
('Trop-plein zinc 100x100', 'Étanchéité', 'Évacuation', 'U', 28.00, 'Point P', 'Pièce', 20),
('Bande adhésive butyl 100mm 25m', 'Étanchéité', 'Adhésif', 'U', 28.00, 'Point P', 'Rouleau 25m', 20),
('Bande pontage EPDM 10cm 25m', 'Étanchéité', 'Bande', 'U', 38.00, 'Point P', 'Rouleau 25m', 20),
('Géotextile 200g/m² rouleau 100m²', 'Étanchéité', 'Géotextile', 'U', 95.00, 'Point P', 'Rouleau 100m²', 20),
('Drain agricole Ø100 25m', 'Étanchéité', 'Drain', 'U', 28.00, 'Point P', 'Couronne 25m', 20),
('Couvre-joint inox dilatation', 'Étanchéité', 'Profilé', 'ml', 38.00, 'Point P', 'Pièce', 20),
('Hydrofuge silane-siloxane 5L', 'Étanchéité', 'Traitement', 'U', 78.00, 'Point P', 'Bidon 5L', 20),

-- ═══ OUTILLAGE CONSOMMABLE — 30 articles ═══
('Mèche béton SDS+ Ø6 longueur 110mm', 'Outillage', 'Mèche', 'U', 4.50, 'Brico Dépôt', 'Pièce', 20),
('Mèche béton SDS+ Ø8 longueur 160mm', 'Outillage', 'Mèche', 'U', 5.50, 'Brico Dépôt', 'Pièce', 20),
('Mèche béton SDS+ Ø10 longueur 210mm', 'Outillage', 'Mèche', 'U', 6.50, 'Brico Dépôt', 'Pièce', 20),
('Mèche béton SDS+ Ø12 longueur 260mm', 'Outillage', 'Mèche', 'U', 8.50, 'Brico Dépôt', 'Pièce', 20),
('Coffret mèches béton 5 pièces SDS+', 'Outillage', 'Mèche', 'coffret', 14.00, 'Brico Dépôt', 'Coffret 5 pcs', 20),
('Mèche bois Ø6 (boîte 10)', 'Outillage', 'Mèche', 'boîte', 8.50, 'Brico Dépôt', 'Boîte 10', 20),
('Mèche bois Ø8 (boîte 10)', 'Outillage', 'Mèche', 'boîte', 9.50, 'Brico Dépôt', 'Boîte 10', 20),
('Mèche métal HSS Ø3 (boîte 10)', 'Outillage', 'Mèche', 'boîte', 6.50, 'Brico Dépôt', 'Boîte 10', 20),
('Mèche métal HSS Ø6 (boîte 10)', 'Outillage', 'Mèche', 'boîte', 9.50, 'Brico Dépôt', 'Boîte 10', 20),
('Disque diamant Ø125 universel', 'Outillage', 'Disque', 'U', 18.00, 'Brico Dépôt', 'Pièce', 20),
('Disque diamant Ø230 universel', 'Outillage', 'Disque', 'U', 38.00, 'Brico Dépôt', 'Pièce', 20),
('Disque diamant Ø125 carrelage', 'Outillage', 'Disque', 'U', 24.00, 'Point P', 'Pièce', 20),
('Disque à tronçonner métal Ø125 (boîte 10)', 'Outillage', 'Disque', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 10', 20),
('Lame scie circulaire 24 dents Ø190', 'Outillage', 'Lame', 'U', 14.00, 'Brico Dépôt', 'Pièce', 20),
('Lame scie sauteuse bois (lot 5)', 'Outillage', 'Lame', 'lot', 12.00, 'Brico Dépôt', 'Lot 5', 20),
('Lame scie sauteuse métal (lot 5)', 'Outillage', 'Lame', 'lot', 14.00, 'Brico Dépôt', 'Lot 5', 20),
('Vis bois 4x40 Torx (boîte 200)', 'Outillage', 'Vis', 'boîte', 12.00, 'Brico Dépôt', 'Boîte 200', 20),
('Vis bois 5x60 Torx (boîte 100)', 'Outillage', 'Vis', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 100', 20),
('Vis bois 6x80 Torx (boîte 50)', 'Outillage', 'Vis', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 50', 20),
('Vis bois 6x120 Torx (boîte 50)', 'Outillage', 'Vis', 'boîte', 18.00, 'Brico Dépôt', 'Boîte 50', 20),
('Cheville Molly 4x46 (boîte 100)', 'Outillage', 'Cheville', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 100', 20),
('Cheville Fischer SX 8x40 (boîte 100)', 'Outillage', 'Cheville', 'boîte', 8.50, 'Brico Dépôt', 'Boîte 100', 20),
('Cheville Fischer SX 10x50 (boîte 50)', 'Outillage', 'Cheville', 'boîte', 9.50, 'Brico Dépôt', 'Boîte 50', 20),
('Cheville à frapper 8x80 (boîte 100)', 'Outillage', 'Cheville', 'boîte', 14.00, 'Brico Dépôt', 'Boîte 100', 20),
('Vis béton TBC 8x80 (boîte 50)', 'Outillage', 'Vis', 'boîte', 18.00, 'Point P', 'Boîte 50', 20),
('Pointe acier 50mm (boîte 1kg)', 'Outillage', 'Clou', 'boîte', 6.50, 'Brico Dépôt', 'Boîte 1kg', 20),
('Crayon de chantier rouge (lot 12)', 'Outillage', 'Marquage', 'lot', 4.50, 'Brico Dépôt', 'Lot 12', 20),
('Cordeau traceur poudre rouge 30m', 'Outillage', 'Marquage', 'U', 14.00, 'Brico Dépôt', 'Pièce', 20),
('Sac à gravats 70L PE renforcé (lot 10)', 'Outillage', 'Évacuation', 'lot', 6.50, 'Brico Dépôt', 'Lot 10', 20),
('Big bag 1m³ 1500kg (la pièce)', 'Outillage', 'Évacuation', 'U', 9.50, 'Brico Dépôt', 'Pièce', 20);

END $$;

-- ═══════════════════════════════════════════════════════════════════════════
-- VÉRIFICATION POST-SEED :
--   SELECT count(*) FROM public.articles_catalogue WHERE user_id IS NULL;
--   → doit retourner 500 (~)
--
--   SELECT categorie, count(*)
--     FROM public.articles_catalogue WHERE user_id IS NULL
--     GROUP BY categorie ORDER BY count DESC;
-- ═══════════════════════════════════════════════════════════════════════════
